apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: workshop-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: mongo
    deploymentconfig: mongo
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: mongo
        deploymentconfig: mongo
    spec:
      containers:
        - image: mongo:latest
          imagePullPolicy: Always
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-volume-1
            - mountPath: /data/db
              name: mongo-volume-2
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mongo-volume-1
          persistentVolumeClaim:
            claimName: mongo-storage-claim-config
        - name: mongo-volume-2
          persistentVolumeClaim:
            claimName: mongo-storage-claim-data
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mongo
        from:
          kind: ImageStreamTag
          name: 'mongo:latest'
          namespace: workshop-demo
      type: ImageChange